name: mission_app
description: A new Flutter application.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: ^3.1.0
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9
  shared_preferences: ^0.5.12+4
  pdf: ^2.0.0
  printing: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
  - images/


